travis:
  secure:
    BINSTAR_TOKEN: W8lYlv3Gcyq5nZu10QFNcoDXsgbwRGPl3g5rerzayvpW2Cs/MlKlMZ6FOHpfH6wXR0DTkprL3ykf1fTV6ioXAYS/OQc4SCHypSWWlgWgkWLeRP8/RPr4vF8NiJKDp+ZI3n2ssX8OZGiOLo0PbkGFA0OLPl/6hF0I3NslxDZxTdB+oGSpQZvflRYA7py97tJMVJeSa4ZNdutl9npRl44MqBa+tKaOYcHti2RgXj5CPpWsJ7OmPQIaPxHUBLGJnTq/LEWbDVsL8XQXO6yr/x43nFLKtZeLzavc39kuJaPCLSmpJBKGhcLaRJaKVtNzHgfZBLsXViPta+kMYxR8pqJV+x2ACTPtxb//8/ylWCMc0te54lhiLPVRbUsgPPAkjIs+6U8F5QmouYt5p50EIh85DoSUZb/opmUNXpW5fImwyVWJ2Iu5y+I9YP6zAJBLXIonGoRZggudKiJS/yjNRkxYax3muEyvoXpEBLE8A1F253ahjV9qzBTqCU74uosQN87z8YJoFxZi/sT8DRElapoMktXcIKV0H4OdFMi2GMnkCh/TvKc3C59Uem8X9LSOb2guveVbgYVl5T5GSNc8N/8MCZUMtRvAj9tCbrECJVXyxMiQnhm6/rySKgak3CuQwYT8Ua30WtczOyg0XVkKJL6uiuG8sGhSgH8QlbPGBPUVMvU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
