travis:
  secure:
    BINSTAR_TOKEN: iNO8t0HizwLE3aSg/j0WKyxtv+7/Jx+a9KKVe9SVSJsk4Oq18T7ZE/3+GH/4DRNY72jNgmDLLlDaLXWgcd2Dx4re/ISRM1IxOM615ntkEbwsL7boqJ2dS/5Blyxx1afYZEMLtdqseUH7+z8vqHIJd3F4lMAHQmIVFzIQl+RFHg935YuannTNNs0xFezs1/1rSyGJkFim5HihghQyPUsgNwj1UM/yjmBJlMSIdXbs9s2DJhAESqGWMlDBmK+oCZ20MXLS2pKF9luL7iTifouySPbL2Z/Pbg+o7DPBW+7deAslriKEYSPgi/ZNHEoJJ8ATnf8aZffm+RjmY8M6D1BI5KitKS3lvSsWGHvLPpmk0tp+w//A9MtNOJe+kyqQtPjZFM5CgnPfLvA42J3kUt7JlemIaW5YEcdfxIpd3XIUrIIn7cfMsPqgFnEYF+o/YQGSnoUeIYUwasFEv8InTjDhu6cy5KWVb8AkwhpQhZYrMDk6Hm42sL3q5TNWJYzsM9IKFAEDfBGBszwTc+xH6wAnSCbwX+7fpco9/JEJGn0thEV5GcwldDmqPSRc51zpiUsVMcusOcnCzCmuapVEhQuThF5B9jnRiRAbOQFZ5nw6i56w7DWNcbCVxTyGdDN2AkUksiZEe5wtjDLKrd+BHhnUP/nww9y8hIQx3sACCPpia74=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
